views/index.html, views/layout.html
[FPO-192](https://transformuk.atlassian.net/browse/FPO-192)
- it is the new landing page
- Tested
=> FPO-192 Dev Hub landing page

.env.development, package.json, src/app.ts, src/routes/dashboardRoutes.ts, src/services/apiService.ts, views/dashboard.html, yarn.lock
[FPO-215](https://transformuk.atlassian.net/browse/FPO-215)
I am doing this because: 
- SCP will handle user authentication
- Tested
=> FPO-215 Integrate with SCP

spec/controllers/dashboardControllerSpec.ts, spec/presenters/dashboardPresenterSpec.ts, spec/routes/dashboardRoutesSpec.ts, src/controllers/dashboardController.ts, src/controllers/keyController.ts, src/controllers/revokeController.ts, src/presenters/dashboardPresenter.ts, src/routes/dashboardRoutes.ts, src/services/apiService.ts, views/dashboard.html, views/keySuccessPage.html, views/newKey.html, views/revoke.html
BAU
- This was changed in the backend and is consistent
- Tested
=> BAU: Fixes fpoId naming

.circleci/config.yml, .env.development, src/app.ts, src/config/cognitoAuth.ts, src/config/scpAuth.ts, terraform/.terraform.lock.hcl, terraform/README.md, terraform/data.tf, terraform/iam.tf, terraform/main.tf, terraform/versions.tf
FPO-254
- This is required to configure SCP
- Tested
=> FPO-254: Consume and expose SCP integration secrets to app

.env.development, src/app.ts, src/config/scpAuth.ts, src/controllers/keyController.ts, src/routes/dashboardRoutes.ts, views/layout.html
[FPO-243](https://transformuk.atlassian.net/browse/FPO-243)
-
see ticket [FPO-243](https://transformuk.atlassian.net/browse/FPO-243) for details
- Tested
=> FPO-243 fix create api key issue

spec/controllers/dashboardControllerSpec.ts, src/app.ts, src/controllers/dashboardController.ts, src/controllers/verificationController.ts, src/presenters/dashboardPresenter.ts, src/routes/applicationRoutes.ts, views/back-button.njk, views/checkVerification.html, views/completion.html, views/dashboard.html, views/index.html, views/keySuccessPage.html, views/layout.html, views/revoke.html, views/verification.html
https://transformuk.atlassian.net/browse/FPO-225
- Tested the flow on local and will do on dev as a clickable walkthrough
=> Changes to UI pages

src/controllers/keyController.ts, src/presenters/apiKeyPresenter.ts, src/services/apiService.ts, views/keySuccessPage.html, views/revoke.html
BAU
- This is required to fix the playwright scenarios
- Tested
=> BAU: Fixes inset and panel copy after creating key

.circleci/config.yml
=> BAU: Pre-commit command

src/presenters/dashboardPresenter.ts, views/dashboard.html, views/layout.html
=> FPO-242: Incorporate feedback on the dashboard page

.circleci/config.yml
FPO-259
- Integrate e2e tests on dev and staging
- We need to prove our changes aren't breaking the integration between the layers
- Tested
=> FPO-259: Integrate e2e tests on feature and merge

src/presenters/dashboardPresenter.ts
=> Add * over X when hiding the API

views/dashboard.html, views/layout.html
https://transformuk.atlassian.net/browse/FPO-236
Footer links across all pages
- [] Removed
- [] Altered
-
- Tested
=> FPO 236 footer

.pre-commit-config.yaml, src/app.ts, src/routes/index.ts, views/checkVerification.njk, views/completion.njk, views/dashboard.njk, views/delete.njk, views/index.njk, views/keySuccessPage.njk, views/layout.njk, views/newKey.njk, views/revoke.njk, views/verification.njk
- Move to njk extension
- Lint all njk files
- Adds hook for njk files
- These templates are a mess
- Tested
=> BAU: Lint njk files

views/index.njk, views/layout.njk
https://transformuk.atlassian.net/browse/FPO-236
- [] Removed
- [] Altered
-
- Tested
=> FPO-236-footer

views/index.njk
BAU
- This is breaking e2e tests
- Tested
=> BAU: Debug start button

views/index.njk
BAU
- This is part of our feedback from Hazel
- Tested
=> BAU: Fixes is start button

package.json, src/controllers/keyController.ts, src/presenters/apiKeyPresenter.ts, src/routes/dashboardRoutes.ts, src/services/apiService.ts, views/dashboard.njk, views/delete.njk, views/keySuccessPage.njk, views/newKey.njk, views/revoke.njk, yarn.lock
[FPO-245](https://transformuk.atlassian.net/browse/FPO-245)
-
- Tested
=> FPO-245 Review content and add validation error to new key form

views/verification.njk
https://transformuk.atlassian.net/browse/FPO-269
-
- Tested
=> FPO-269-content

src/controllers/cookiesController.ts, src/controllers/privacyPolicyController.ts, src/routes/index.ts, views/cookies.njk, views/layout.njk, views/privacyPolicy.njk
[FPO-238](https://transformuk.atlassian.net/browse/FPO-238)
[FPO-247](https://transformuk.atlassian.net/browse/FPO-247)
-
- Tested
=> FPO-238: Cookies and Privacy Policy placeholder pages

views/completion.njk, views/dashboard.njk, views/keySuccessPage.njk, views/newKey.njk, views/revoke.njk
https://transformuk.atlassian.net/browse/FPO-270
-
- Tested
=> FPO-270-UI-Changes

views/checkVerification.njk
https://transformuk.atlassian.net/browse/FPO-240
-
- Tested
=> FPO-240-content

src/config/main-navigation-options.ts
https://transformuk.atlassian.net/browse/FPO-271
-
- Tested
=> FPO-271-Header links

src/controllers/verificationController.ts, src/services/userService.ts, terraform/config_staging.tfvars
=> BAU: Code review

src/routes/index.ts
See [FPO-275](https://transformuk.atlassian.net/jira/software/projects/FPO/boards/116?selectedIssue=FPO-275)
- the check your answers page is not appearing due to the registration process
- Tested
=> Allow verification pages to appear

package.json, src/app.ts, src/controllers/verificationController.ts, views/checkVerification.njk, views/verification.njk, yarn.lock
[FPO-256](https://transformuk.atlassian.net/jira/software/projects/FPO/boards/116?selectedIssue=FPO-256)
- we need to display the answers in the next page and also if the user comes back to page
- Tested
=> FPO-256 Storing users answers in the session

.env.development, src/controllers/verificationController.ts, src/routes/index.ts, terraform/README.md, terraform/config_development.tfvars, terraform/config_production.tfvars, terraform/config_staging.tfvars, terraform/main.tf, terraform/variables.tf, views/verification-form.njk, views/verification.njk
[FPO-284](https://transformuk.atlassian.net/browse/FPO-284)
- we need to validate the information before preparing the email
- Tested
=> FPO-284 Validate user inputs

globals.d.ts, package.json, src/controllers/verificationController.ts, src/services/emailService.ts, terraform/README.md, terraform/config_development.tfvars, terraform/config_production.tfvars, terraform/config_staging.tfvars, terraform/data.tf, terraform/main.tf, terraform/variables.tf, tsconfig.json, yarn.lock
[FPO-255](https://transformuk.atlassian.net/browse/FPO-255)
- we need to inform the user the progress of their application
- Tested
=> FPO-255 Add GovNotify configuration

src/config/registration.ts
[FPO-274](https://transformuk.atlassian.net/browse/FPO-274)
-
- Tested
=> FPO-274 Check Organisation status after creating the user

src/controllers/verificationController.ts
Fix group id in Verification Controller
- it is not working 
- Tested
=> Fix group id in Verification Controller

src/config/registration.ts, src/services/organisationService.ts
https://transformuk.atlassian.net/browse/FPO-290
I am doing this because: api changed
-
- Tested
=> FPO-290_changes

src/app.ts, terraform/README.md, terraform/data.tf, terraform/iam.tf, terraform/main.tf
[FPO-307](https://transformuk.atlassian.net/browse/FPO-307)
- it is security risk to commit this value into Github
- Tested
=> FPO-307 Remove cookie signing secret

src/config/registration.ts, src/controllers/verificationController.ts, src/services/commonService.ts, src/services/emailService.ts, src/services/organisationService.ts, src/services/userService.ts, views/verification-form.njk
[FPO-294](https://transformuk.atlassian.net/browse/FPO-294)
- it is required for verification purpose
- Tested
=> Fpo 294 storing email data

views/checkVerification.njk, views/dashboard.njk, views/index.njk, views/rejectedPage.njk, views/verification-form.njk, views/verification.njk
[FPO-306](https://transformuk.atlassian.net/browse/FPO-306)
-
- Tested
=> FPO-306 update support email address

.eslintrc.js, src/app.ts, src/config/security.ts, src/controllers/deleteController.ts, src/controllers/keyController.ts, src/controllers/revokeController.ts, src/controllers/verificationController.ts, views/back-button.njk, views/checkVerification.njk, views/completion.njk, views/dashboard.njk, views/delete.njk, views/keySuccessPage.njk, views/layout.njk, views/newKey.njk, views/rejectedPage.njk, views/revoke.njk, views/verification.njk
FPO-328
- The inline JS was broken due to the new CSP
=> FPO-328: Adding a nonce to the CSP so that JS isn't broken

src/app.ts, views/404.njk, views/500.njk
[FPO-326](https://transformuk.atlassian.net/browse/FPO-326)
- it is required 
- Tested
=> FPO-326 add 404 and 500 page

src/app.ts, src/config/registration.ts, src/config/security.ts, src/controllers/verificationController.ts, src/presenters/apiKeyPresenter.ts, src/services/apiService.ts, src/services/organisationService.ts, src/services/userService.ts, views/checkVerification.njk, views/completion.njk, views/cookies.njk, views/dashboard.njk, views/delete.njk, views/index.njk, views/keySuccessPage.njk, views/layout.njk, views/newKey.njk, views/privacyPolicy.njk, views/rejectedPage.njk, views/revoke.njk, views/verification.njk
- It needed some tidying up
- Potential for URL injection which might allow someone to access other user's records
=> FPO-392: A bit of tidying up content and whatnot

public/robots.txt
HMRC-481
Disallow indexing by search crawlers
=> HMRC-481-Obfuscate-FPO-developer-hub-from-crawlers-indexers
